---
services:
  openssh-server:
    image: lscr.io/linuxserver/openssh-server:latest
    container_name: openssh-server-andriani
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - USER_NAME=${USER_NAME:-admin}
      # Generate your public SSH key 
      - PUBLIC_KEY=${PUBLIC_KEY}
    volumes:
      # Stores config in a 'config' folder in the current directory
      - ./config:/config
    ports:
      - "${SSH_PORT:-2222}:2222"
    restart: unless-stopped